### ISSUE TITLE
Can't install plugin for 6.3.0

### ISSUE THREAD

**Issue by MClode** [codelibs/elasticsearch-dataformat#49]
> -> Downloading org.codelibs:elasticsearch-dataformat:6.3.0 from maven central
> [=================================================] 100%?? 
> Warning: sha512 not found, falling back to sha1. This behavior is deprecated and will be removed in a future release. Please update the plugin to use a sha512 checksum.
> ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
> The command '/bin/sh -c bin/elasticsearch-plugin install discovery-ec2 --batch && bin/elasticsearch-plugin install repository-s3 --batch && bin/elasticsearch-plugin install org.codelibs:elasticsearch-dataformat:6.3.0 --batch && sed -e '/^-Xm/s/^/#/g' -i /usr/share/elasticsearch/config/jvm.options' returned a non-zero code: 2

Not sure if I am doing something wrong (its undocumented how to install for 6.x) or if, as the text states, some changes need to be made to the .zip

**Comment by marevol** [comment]
Fixed in 6.3.1
