### ISSUE TITLE
Add support for elasticsearch 6.5

### ISSUE THREAD

**Issue by fbaligand** [codelibs/elasticsearch-dataformat#52]
Hi,

It would be great to add support for Elasticsearch 6.5 !

**Comment by marevol** [comment]
Fess 12.4 will be released in this week...

**Comment by fbaligand** [comment]
Great news !

Fabien

**Comment by fbaligand** [comment]
I just tested last version, and it works great on Elasticsearch 6.5!
=> Thanks a lot!

I close the issue.
